### ISSUE TITLE
could not find `udv_si` function

### ISSUE THREAD

**Issue by ml3958** [stephenslab/flashr#100]
hi, thanks for developing this amazing method. I have been trying to reproduce the non-negative loading estimation based on this[ link](https://willwerscheid.github.io/MASHvFLASH/MASHvFLASHnn2.html), but found that `udv_si()` function is no longer available. 

I downloaded an older version instead by `install_github("stephenslab/flashr@v0.5-6",build_vignettes=TRUE,force = TRUE)` but still couldn't find this `udv_s()`.

Any suggestions? Thank you!

**Comment by stephens999** [comment]
i'm not sure what code your are running as the link you give just loads pre-computed results.
The udv_si function is not exported, but it is there, so it can be accessed via flash:::udv_si

However, we are in the process of both replacing flashr with an improved (faster) package,
and better documenting its interface, so I'm not sure what best advice for you in short term is. 
I'll let @willwerscheid advise.

**Comment by ml3958** [comment]
Thanks for the suggestion! I was able to use this function by `flashr:::udv_si` (Previously I was using two colons `flashr::udv_si`). 

Looking forward to using the newer version of flashr!
