### ISSUE TITLE
Automatic scaling of the data?

### ISSUE THREAD

**Issue by ml3958** [stephenslab/flashr#101]
Hi, 

I wonder does flashr automatically performs some types of data normalization or scaling? 

I fitted a model and compared my input value with the fitted value, and found the fitted value looks like being centered (see below).  If yes, can I turn this process off?

<img width="443" alt="image" src="https://user-images.githubusercontent.com/14187807/133359504-894f0a52-6b7f-47ca-9c3b-4255a14948f0.png">

Thank you in advance and looking forward to your reply!

Best, Menghan

**Comment by willwerscheid** [comment]
No, `flashr` doesn't do any scaling/normalization. Could you attach code? I can try to have a look.

**Comment by ml3958** [comment]
Thanks for your reply @willwerscheid. I was basically running a sample code from this [analysis](https://willwerscheid.github.io/MASHvFLASH/MASHvFLASHnn.html).  

My input is a sparse matrix with positive float values from [0-400].  Please [click](https://github.com/stephenslab/flashr/files/7166717/sample_data.txt) to download

Below is the code

```{r }

my_init_fn <- function(Y, K = 1) {
  ret = flashr:::udv_si(Y, K)
  pos_sum = sum(ret$v[ret$v > 0])
  neg_sum = -sum(ret$v[ret$v < 0])
  if (neg_sum > pos_sum) {
    return(list(u = -ret$u, d = ret$d, v = -ret$v))
  } else
    return(ret)
}



ebnm_fn = "ebnm_ash"
ebnm_param = list(l = list(mixcompdist = "normal",
                           optmethod = "mixSQP"),
                  f = list(mixcompdist = "+uniform",
                           optmethod = "mixSQP"))

strong= read.delim('./nmf/sample_data.txt',sep='\t',header = F)
strong_data <- flash_set_data(strong, S = 1)


# var_type = "const" ----------------------------------------------------

t_g_const <- system.time(
  fl_g_const <- flashr:::flash_greedy_workhorse(strong,
                                                Kmax = 1000,
                                                var_type = "constant",
                                                ebnm_fn = ebnm_fn,
                                                ebnm_param = ebnm_param,
                                                init_fn = "my_init_fn",
                                                stopping_rule = "factors",
                                                tol = 1e-3,
                                                verbose_output = "odF")
) # 26 factors in 3.3 min
saveRDS(fl_g_const, "./nmf/fl_g_const_k1000.rds")
saveRDS(t_g_const, "./nmf/t_g_const_k1000.rds")

t_b_const <- system.time(
  fl_b_const <- flashr:::flash_backfit_workhorse(strong,
                                                f_init = fl_g_const,
                                                var_type = "constant",
                                                ebnm_fn = ebnm_fn,
                                                ebnm_param = ebnm_param,
                                                stopping_rule = "factors",
                                                tol = 1e-3,
                                                verbose_output = "odF")
) # backfit in 13.1 min
saveRDS(fl_b_const, "./nmf/fl_b_const_k1000.rds")
saveRDS(t_b_const, "./nmf/t_b_const_k1000.rds")
```

>

**Comment by willwerscheid** [comment]
`ldf$l %*% t(ldf$f)` doesn't give fitted values. Loadings and factors are normalized so that the l_2 norm is equal to one, and the scale factor is returned in `ldf$d`, so you'd need to write `ldf$l %*% diag(ldf$d) %*% t(ldf$f)`. Or, more simply, you can use `flash_get_lf` to get fitted values.

**Comment by ml3958** [comment]
I got the results with `ldf$l %*% diag(ldf$d) %*% t(ldf$f)`

<img width="458" alt="image" src="https://user-images.githubusercontent.com/14187807/133466593-dc9657e9-4fd9-4f67-a999-637e447ed26e.png">

Many thanks!
