### ISSUE TITLE
possible warmstart

### ISSUE THREAD

**Issue by stephens999** [stephenslab/flashr#13]
it would be easy in principle to use the fitted g as a warmstart. However there are complications because we prune the g coming out of ash, so the grid being used in such a warmstart would be very low resolution.... the easiest way to deal with this would be modify ashr to not prune the returned g (ie we could do the pruning just for posterior calculations, but return full g).
(Originally this was impossible because of the way the objective fn was being computed, but that
is not an issue any more)

**Comment by willwerscheid** [comment]
We've implemented using fitted g, and ashr no longer prunes, so I think this issue can be closed.
