### ISSUE TITLE
extending the use of partially fixed factors/loadings

### ISSUE THREAD

**Issue by stephens999** [stephenslab/flashr#14]
currently covariate can be added via flash_add_fixed_loading
These can be "partially fixed" in that NAs will be esitmated.

I have in mind that it may be useful to add a partially-fixed loading where
the 0s are fixed and the non-zero entries get reesitmated. The idea is
that you could add a loading corresponding to a "gene set" that has non-zero
entries only in the gene set. These will then be re-estimated during fitting.
(could initialize by PCA only on the gene set expression?)

When doing this it might be helpful to give the loadings names too.... (so we know which
gene set each loading corresponds to)

**Comment by willwerscheid** [comment]
This issue can be closed. (The names issue is also in #11 .)
