### ISSUE TITLE
faster init when Y is completely observed?

### ISSUE THREAD

**Issue by stephens999** [stephenslab/flashr#22]
At the moment we use softImpute for default initialization.
When Y is completely observed maybe regular svd would be faster? I haven't checked....

**Comment by willwerscheid** [comment]
When a matrix does not have missing data, softImpute (type=“svd”) calculates the SVD twice. So it takes twice as long. But softImpute (type=“als”) generally seems to be faster than svd, by a factor of about 2 (at least with the default maximum number of iterations). (As an interesting side note, you get very little savings by limiting the number of singular values that svd computes.)
