### ISSUE TITLE
flash_plot_factors is broken and other plotting issues

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/flashr#43]
It sends all of L and F to plot_one_factor (instead of one factor at a time, one by one). The plotting function expects $Factor but when L and F are matrices it sees $Factor.1, $Factor.2, etc. When we fix, we should allow the data to be passed in as a matrix rather than requiring a flash data object (as with other user-facing functions). Also add space to plot title ("PVE = x" instead of "PVE= x"). Finally, plot_one_factor should not be exported.

**Comment by willwerscheid** [comment]
Current thoughts: make plotting functions into a single `plot` S3 method. Allow options `factors_kset` (default = NULL) and `loadings_kset` (default = NULL) to plot individual factors/loadings. It would be nice to have the user click through the plots like in `plot(lm)`; I'm not sure how difficult that would be to implement.

**Comment by pcarbo** [comment]
@willwerscheid Alternatively you can use `plot_grid` from the `cowplot` package to arrange the plots together.
