### ISSUE TITLE
remove flash_add_factors_from data from interface?

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/flashr#51]
This is kind of a weird and confusing function to export. I'm thinking it would be better to remove it and if we do in fact want to retain the functionality we could add a parameter option to flash_add_greedy (like `optimize_factors = TRUE` -- after all, flash_add_greedy just calls flash_add_factors_from_data and then optimizes them). Because it's not totally clear, especially from the descriptions, what the difference is between flash_add_factors_from_data (is this not done greedily?) and flash_add_greedy (isn't that also from data?) and why I would want to use one or the other.

**Comment by stephens999** [comment]
Fine by me

**Comment by willwerscheid** [comment]
I think we still need to export this function (see usage in vignette). Maybe we could change the name to `flash_init_factors_from_data`? I think `flash_init_lf` could use a better name as well -- or maybe we don't need to export it? (`flash_add_fixed_loadings` possibly meets the same need.) Finally, `flash_update_precision` most likely doesn't need to be exported.
