### ISSUE TITLE
think about removing factor entirely if zero in flash_add_greedy

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/flashr#53]
It makes sense to keep factors around if they're zeroed out after a nullcheck during a backfit (so that the indexing isn't affected), but I think it's safe to remove a zeroed-out factor (or rather, a factor that is "effectively zero") if it's the last one added in a call to `flash_add_greedy`. (And there will always be such a factor unless `Kmax` is reached!) Keeping it around makes `flash_get_k` inaccurate (or at least unintuitive), as it will count the zeroed-out factor. This could be done very easily here:
`if (is_tiny_fl(f, flash_get_k(f)))
   break`

**Comment by stephens999** [comment]
i think i did not do this (remove zero factors) because i wanted to avoid complications of, for example, having to deal with edge cases of a flash object with no factors. I agree get_k is unintuitive. How about we write summary.flash to count only the non-zero factors by default?

**Comment by willwerscheid** [comment]
What if we automatically removed it only for flash_add_greedy and only if it's the last factor added (as long as it doesn't leave us with an empty flash object). So , for example, `old_f = f; f = flash_r1(...); if (is_tiny_fl(f, flash_get_k(f)) && flash_get_k(f) > 1) f = old_f`?
