### ISSUE TITLE
add summary method

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/flashr#55]
@stephens999 
> we should produce a summary method for flash that produces a useful summary (in the spirit of summary.lm) and perhaps points the user to the main flash_get functions

**Comment by pcarbo** [comment]
@willwerscheid The recommended approach (see `lm` for an example) is to define a `summary.flash` function, which outputs an object of type `c("summary.flash","list")`, and a function `print.summary.varbvs`, which prints the `summary.flash` object to the screen, and outputs this object "invisibly". See also my [varbvs code](https://raw.githubusercontent.com/pcarbo/varbvs/master/varbvs-R/R/summary.varbvs.R) for an example.
