### ISSUE TITLE
remove seed parameter?

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/flashr#80]
I think we can trust the user to set seeds when necessary. `softImpute`, for example, doesn't include a seed parameter. Nor does `glmnet`, etc... the usual practice seems to be to leave it out.

**Comment by pcarbo** [comment]
@willwerscheid Agreed!

**Comment by stephens999** [comment]
i’d much rather keep the seed as it seems a sensible default to set the
seed and make things produce the same answer every time….
i would argue this is standard (and best) practice with command line
programs. eg I do that in PHASE.
From experience i think it is optimistic to trust users to do this
(including ourselves!)
